lib/zz_web/router.ex
defmodule ZzWeb.Router do
  use ZzWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.OnePlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ZzWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/grains", GrainController, :index
    post "/grains", GrainController, :index
    get "/index", HomeController, :index
    get "/fengya", FengYaController, :index
    get "/phone", UserController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ZzWeb do
  #   pipe_through :api
  # end
end

lib/zz/grains.ex
defmodule Zz.Grains do
  @moduledoc """
  The Grains context.
  """
  import Ecto.Query, only: [from: 2]

  alias Zz.Grains.Grain, as: Ggg
  alias Zz.Repo, as: Gr

  def search_grains(user_input) do
    Ggg
    |> Ecto.Query.order_by(desc: :inserted_at)
    # |> Ecto.Query.limit(1000)
    # |> offset(i)
    |> Gr.all()
    |> Enum.reject(&(String.match?(&1.address, ~r/#{user_input}/) == false))
  end

  def list_grains do
    Ggg
    |> Ecto.Query.limit(3000)
    |> Ecto.Query.where([l], l.latest_price != "0")
    |> Ecto.Query.order_by(desc: :inserted_at)
    |> Gr.all()
  end

  def grains_list(x, y) do
    case y do
      "latest_price" ->
        Ggg
        |> Ecto.Query.where([l], l.latest_price != "0")
        |> Ecto.Query.limit(3000)
        |> Ecto.Query.order_by(desc: :inserted_at)
        |> Gr.all()

      "starting_price" ->
        [f] = Ecto.Query.from(p in Ggg, select: min(p.starting_price)) |> Gr.all()

        Ggg
        |> Ecto.Query.where(starting_price: ^f)
        # |> Ecto.Query.where([g], g.latest_price != "0")
        |> Ecto.Query.order_by(desc: :inserted_at)
        |> Gr.all()

      "year" ->
        Ggg
        |> Ecto.Query.where(year: ^x)
        |> Ecto.Query.limit(3000)
        # |> Ecto.Query.where([g], g.latest_price != "0")
        |> Ecto.Query.order_by(desc: :inserted_at)
        |> Gr.all()

      "address" ->
        [xx, _] = x |> String.split("(")

        Ggg
        |> Ecto.Query.where(address: ^xx)
        |> Ecto.Query.limit(3000)
        # |> Ecto.Query.where([g], g.latest_price != "0")
        |> Ecto.Query.order_by(desc: :inserted_at)
        |> Gr.all()

      "variety" ->
        Ggg
        |> Ecto.Query.where(variety: ^x)
        |> Ecto.Query.limit(3000)
        # |> Ecto.Query.where([g], g.latest_price != "0")
        |> Ecto.Query.order_by(desc: :inserted_at)
        |> Gr.all()
    end
  end
end

lib/zz/grains/grain.ex
defmodule Zz.Grains.Grain do
  use Ecto.Schema
  import Ecto.Changeset
  @derive {Jason.Encoder, except: [:__meta__, :inserted_at, :updated_at, :id]}
  schema "grains" do
    field :address, :string
    field :grade, :string
    field :latest_price, :string
    field :mark_number, :string
    field :market_name, :string
    field :starting_price, :string
    field :status, :string
    field :trade_amount, :string
    field :trantype, :string
    field :variety, :string
    field :year, :string

    timestamps()
  end

  @doc false
  def changeset(grain, attrs) do
    grain
    |> cast(attrs, [
      :address,
      :mark_number,
      :grade,
      :latest_price,
      :market_name,
      :starting_price,
      :status,
      :trade_amount,
      :variety,
      :year,
      :trantype
    ])
    |> validate_required([
      :address,
      :mark_number,
      :grade,
      :latest_price,
      :market_name,
      :starting_price,
      :status,
      :trade_amount,
      :variety,
      :year,
      :trantype
    ])
    |> unique_constraint(:mark_number)
  end
end

lib/zz_web/controllers/grain_controller.ex
defmodule ZzWeb.GrainController do
  use ZzWeb, :controller
  alias Zz.Grains, as: Gg

  def index(conn, params) do
    grains =
      if Map.has_key?(params, "td_data") && params["td_data"] != "" do
        [x, y] = params["td_data"] |> String.split(",")
        Gg.grains_list(x, y)
      else
        if Map.has_key?(params, "search") do
          Gg.search_grains(params["search"])
        else
          Gg.list_grains()
        end
      end

    {:ok, pid} = Agent.start_link(fn -> 0 end)
    render(conn, "index.html", grains: grains, pid: pid)
  end
end

lib/zz_web/views/grain_view.ex
defmodule ZzWeb.GrainView do
  use ZzWeb, :view

  def dizeng(pid) do
    Agent.update(pid, fn i -> i + 1 end)
    Agent.get(pid, fn i -> i end)
  end
end

lib/zz_web/templates/grain/index.html.eex
<script charset="utf-8">
  function submitForm(t, tt='zeng'){
    let form = document.getElementById("myform")
    document.getElementById("td_data").value = [t.innerHTML, tt]
    form.submit()
} 
</script>
<div>
  <h3>稻谷历史交易记录</h3>
  <%= form_tag Routes.grain_path(@conn, :index), [id: "myform"] do %>
    <div>
    <label for="">查询已交易粮库（例如“九江”）</label>
    <input type="text" value="" name="search"/>
    <input type="submit" value="搜索">
    </div>
    <table class="qgg-table">
    <thead>
      <tr>
        <td>编号</td>
        <td>交易时间</td>
        <td>交货地址</td>
        <td>类型</td>
        <td>品种</td>
        <td>等级</td>
        <td>年份</td>
        <td>交易数量</td>
        <td>起始价格</td>
        <td>最终价格</td>

      </tr>
    </thead>
    <tbody>
      <%= for redis <- @grains do %>
        <tr>
          <td><%= dizeng(@pid) %></td>
          <td><%= redis.inserted_at |> Timex.to_datetime("Etc/UTC") |> Timex.to_datetime("Asia/Shanghai") |> DateTime.to_naive %></td>
          <td onclick=submitForm(this,"address")><%= redis.address <> "(#{redis.mark_number})" %></td>
          <td><%= redis.trantype %></td>
          <td onclick=submitForm(this,"variety")><%= redis.variety %></td>
          <td><%= redis.grade %></td>
          <td onclick=submitForm(this,"year")><%= redis.year %></td>
          <td><%= redis.trade_amount %></td>
          <td onclick=submitForm(this,"starting_price")><%= redis.starting_price %></td>
          <td><%= redis.latest_price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <input type="hidden" name="td_data" id="td_data" value="" />
  <% end %>
</div>